config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #verb "path",to :"controller_name#controller_action"
  root to: "pages#home" #takes us to the root_path
  get "about", to: "pages#about"
  get "contact",to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
    @members = ["Francisco","Diogo","Joao","Andre"]
    @search = params[:member]
    if @search.present?
      @members = @members.select {|member| member == @search }
    end
  end

  def home

  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails First Lecture</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Back", root_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Here is our about page!</h1>

app/views/pages/contact.html.erb
<h1>Contact page!!</h1>

<% if params[:member].present? %>
  <p>You searched for <%= @search %></p>
<% end %>

<form action="/contact" method="get">
  <input type="text" name="member" value="<%= params[:member] %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<h2>Meet our team!</h2>
<ol>
  <% @members.each do |member| %>
  <li>
    <%= member.capitalize %>
  </li>
  <% end %>
</ol>

app/views/pages/home.html.erb
<h1>HomePage of our Rails App</h1>

<p> Now is <%= Time.now %></p>

<%= link_to "About Us", about_path %>
<%= link_to "Contact Us", contact_path %>